### ISSUE TITLE
Router not working when in "history" mode

### ISSUE THREAD

**Issue by CodebyOmar** [CodebyOmar/whot-app#7]
I want the # sign removed from the URL. Normally when the mode is set to "history" it works, this time around it resfuses to work for me.

**Comment by mykeels** [comment]
What's history mode?

**Comment by CodebyOmar** [comment]
I want the # sign removed from the URL. Normally when the mode is set to "history" it works, this time around it resfuses to work for me.

**Comment by mykeels** [comment]
What does it show when you load the page?

**Comment by CodebyOmar** [comment]
it says cannot GET /newplayer.
Is it advisable to use but NPM and yarn in the same project? I'm suspecting it has something to do with that.

**Comment by CodebyOmar** [comment]
Apparently this is a known issue with the new webpack config for vue. The historyapifallback is not set. Solved -> https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback
