### ISSUE TITLE
Dependency Not Found

### ISSUE THREAD

**Issue by tobiamos** [CodebyOmar/whot-app#8]
it says 
 npm run dev

> whot-app@1.0.0 dev C:\Users\tobid\Desktop\whot-app
> webpack-dev-server --inline --history-api-fallback --progress --config build/webpack.dev.conf.js

 94% asset optimization ERROR  Failed to compile with 1 errors14:58:48

This dependency was not found:

* @/componenets/views/gamePlay/game-play in ./src/router/index.js

To install it, you can run: npm install --save @/componenets/views/gamePlay/game-play
 then when i run ```npm install --save @/componenets/views/gamePlay/game-play```
it says 
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@C:\Program Files\Git\componenets\views\gamePlay\game-play" as it does not contain a package.json file.

**Comment by mykeels** [comment]
I'd have to run this locally to see how it works. I don't have my laptop with me, so this will take at most 24 hours.

@CodebyOmar, could you take a look?

**Comment by mykeels** [comment]
This should be fixed @tobiamos ... could you pull and try again?

**Comment by tobiamos** [comment]
Sure. one sec

**Comment by tobiamos** [comment]
its fixed.
